# Jellyfin Media Server

services:
  jellyfin:
    image: ${JELLYFIN_IMAGE}:${JELLYFIN_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: jellyfin
    networks:
      mediacenter:
        ipv4_address: 172.30.0.120
    devices:
      - /dev/dri:/dev/dri
    ports:
      - ${JELLYFIN_PORT}:8096
    restart: unless-stopped
    environment:
      - PUID=${JELLYFIN_UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/jellyfin-config:/config
      - ${ROOT_DIR}/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_TRAEFIK_NAME}.${DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8096/health && test -d /data/realdebrid-zurg && mountpoint -q /data/realdebrid-zurg"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      overseerr:
        condition: service_healthy
        restart: true
      rclone:
        condition: service_healthy
        restart: true
